services:
  cow-session-docker-compose:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD : 1234
      MYSQL_DATABASE : cowsession
    volumes:
      - ./db/mysql/data:/var/lib/mysql
    ports:
      - '3307:3306'
